<?xml version="1.5"?>
<robot name="gimbal" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find gimbal_controller)/urdf/generic_gimbal_base.xacro"/>
    <xacro:property name="support_height" value="$(arg support_height)"/>
    <xacro:property name="x_resolution" value="$(arg x_resolution)"/>
    <xacro:property name="y_resolution" value="$(arg y_resolution)"/>
    <xacro:property name="h_aov" value="$(arg h_aov)"/>
    <xacro:property name="visualize" value="$(arg visualize)"/>

    <xacro:property name="pi" value="3.1415926535897931"/>

    <link name="world">
    </link>

    <joint name="joint_base" type="fixed">
        <axis xyz="0 0 1"/>
        <!--<limit eff
        ort="10" velocity="<1.0" lower="-1.57" upper="1.57"/>-->
        <origin xyz="0 0 ${support_height/2}" rpy="0 0 0"/>
        <parent link="world"/>
        <child link="base_link"/>
    </joint>

    <link name="base_link">
        <colision>
            <geometry>
                <box size="0.1 0.1 ${support_height}"/>
            </geometry>
        </colision>
        <visual>
            <geometry>
                <box size="0.1 0.1 ${support_height}"/>
            </geometry>
        </visual>
        <inertial>
            <mass value="10"/>
            <xacro:box_inertia x="0.1" y="0.1" z="${support_height}" mass="10"/>
        </inertial>
    </link>

    <joint name="joint_base_1" type="fixed">
        <axis xyz="0 0 1"/>
        <!--<limit eff
        ort="10" velocity="<1.0" lower="-1.57" upper="1.57"/>-->
        <origin xyz="0.25 0 ${support_height/2}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="base_link_1"/>
    </joint>

    <link name="base_link_1">
        <colision>
            <geometry>
                <box size="0.6 0.1 0.1"/>
            </geometry>
        </colision>
        <visual>
            <geometry>
                <box size="0.6 0.1 0.1"/>
            </geometry>
        </visual>
        <inertial>
            <mass value="5"/>
            <xacro:box_inertia x="0.5" y="0.1" z="0.1" mass="5"/>
        </inertial>
    </link>

    <gazebo reference="base_link">
        <material>Gazebo/Orange</material>
    </gazebo>
    <gazebo reference="base_link_1">
        <material>Gazebo/Orange</material>
    </gazebo>


    <xacro:generic_gimbal
            robot_namespace="m210"
            parent_link="base_link_1"
            camera_suffix="labmetro"
            horizontal_fov="${pi/180*h_aov}"
            image_width="${x_resolution}"
            image_height="${y_resolution}"
            image_format="R8G8B8"
            max_range="100"
            visualize="${visualize}"
            type="continuous"
            mass="0.036"
            z="-0.05"
            y="0"
            x="0.25">
    </xacro:generic_gimbal>


</robot>
