gimbal:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------

  yaw_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_yaw
    pid: {p: 0.005, i: 0.05, d: 0.010}

  roll_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_roll
    pid: {p: 0.005, i: 0.05, d: 0.0010}

  pitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_pitch
    pid: {p: 0.01, i: 0.005, d: 0.000}
